'use client';

import React, { createContext, useContext, useState } from 'react';
import { Siemreap, Koulen, Battambang } from 'next/font/google';
import { configData } from '../data/configData';

// Configure Khmer Fonts
const siemreap = Siemreap({
    weight: '400',
    subsets: ['khmer'],
    display: 'swap',
});

const koulen = Koulen({
    weight: '400',
    subsets: ['khmer'],
    display: 'swap',
});

const battambang = Battambang({
    weight: ['400', '700'],
    subsets: ['khmer'],
    display: 'swap',
});

export type Language = 'en' | 'kh';

export type LocalizedString = Partial<Record<Language, string>> & { en: string };

type Translations = {
    [key: string]: LocalizedString;
};

// Dictionary
const dictionary: Translations = {
    // === NAVIGATION ===
    'Home': { en: 'Home', kh: 'ទំព័រដើម' },
    'About Us': { en: 'About Us', kh: 'អំពីយើង' },
    'Company Profile': { en: 'Company Profile', kh: 'ប្រវត្តិក្រុមហ៊ុន' },
    'Leadership': { en: 'Leadership', kh: 'ថ្នាក់ដឹកនាំ' },
    'Quality & Safety': { en: 'Quality & Safety', kh: 'គុណភាព & សុវត្ថិភាព' },
    'Services': { en: 'Services', kh: 'សេវាកម្ម' },
    'Design & Build': { en: 'Design & Build', kh: 'រចនា & សាងសង់' },
    'Infrastructure': { en: 'Infrastructure', kh: 'ហេដ្ឋារចនាសម្ព័ន្ធ' },
    'Project Management': { en: 'Project Management', kh: 'គ្រប់គ្រងគម្រោង' },
    'Systems': { en: 'Systems', kh: 'ប្រព័ន្ធបច្ចេកទេស' },
    'Projects': { en: 'Projects', kh: 'គម្រោង' },
    'Done Projects': { en: 'Completed Projects', kh: 'គម្រោងបានបញ្ចប់' },
    'Implement Projects': { en: 'Project In Progress', kh: 'គម្រោងកំពុងអនុវត្ត' },
    'News': { en: 'News', kh: 'ព័ត៌មាន' },
    'News & Updates': { en: 'News & Updates', kh: 'ព័ត៌មាន & បច្ចុប្បន្នភាព' },
    'Doc Collection': { en: 'Doc Collection', kh: 'ឯកសារ' },
    'Careers': { en: 'Careers', kh: 'ការងារ' },
    'Contact': { en: 'Contact', kh: 'ទំនាក់ទំនង' },
    'About': { en: 'About', kh: 'អំពីយើង' },

    // Nav Sub-descriptions
    'Learn about our history': { en: 'Learn about our history', kh: 'ស្វែងយល់អំពីប្រវត្តិរបស់យើង' },
    'Meet our team': { en: 'Meet our team', kh: 'ជួបជាមួយក្រុមការងារ' },
    'Our standards': { en: 'Our standards', kh: 'ស្តង់ដាររបស់យើង' },
    'Full lifecycle solutions': { en: 'Full lifecycle solutions', kh: 'ដំណោះស្រាយពេញលេញ' },
    'Building the backbone': { en: 'Building the backbone of communities', kh: 'កសាងឆ្អឹងខ្នងនៃសហគមន៍' },
    'Strategic oversight & control': { en: 'Strategic oversight & control', kh: 'ការត្រួតពិនិត្យយុទ្ធសាស្ត្រ & ការគ្រប់គ្រង' },
    'Revitalize existing structures': { en: 'Revitalize existing structures', kh: 'ធ្វើឱ្យរចនាសម្ព័ន្ធដែលមានស្រាប់រស់ឡើងវិញ' },
    'Smart building technologies': { en: 'Smart building technologies', kh: 'បច្ចេកវិទ្យាអគារឆ្លាតវៃ' },
    'View our portfolio': { en: 'View our portfolio', kh: 'មើលស្នាដៃរបស់យើង' },
    'Current developments': { en: 'Current developments', kh: 'ការអភិវឌ្ឍន៍បច្ចុប្បន្ន' },
    'Latest announcements': { en: 'Latest announcements', kh: 'សេចក្តីប្រកាសចុងក្រោយ' },
    'Resources & documents': { en: 'Resources & documents', kh: 'ធនធាន & ឯកសារ' },

    // === COMMON UI ELEMENTS ===
    'Get Quote': { en: 'Get Quote', kh: 'ស្នើសុំតម្លៃ' },
    'Get a Free Quote': { en: 'Get a Free Quote', kh: 'ស្នើសុំតម្លៃឥតគិតថ្លៃ' },
    'Get Free Quote': { en: 'Get Free Quote', kh: 'ទទួលបានការវាយតម្លៃតម្លៃឥតគិតថ្លៃ' },
    'Search...': { en: 'Search...', kh: 'ស្វែងរក...' },
    'View Projects': { en: 'View Projects', kh: 'មើលគម្រោង' },
    'Contact Us': { en: 'Contact Us', kh: 'ទាក់ទងយើង' },
    'Back': { en: 'Back', kh: 'ត្រឡប់ក្រោយ' },
    'Share:': { en: 'Share:', kh: 'ចែករំលែក:' },
    'View All': { en: 'View All', kh: 'មើលទាំងអស់' },
    'View All Projects': { en: 'View All Projects', kh: 'មើលគម្រោងទាំងអស់' },
    'View All News': { en: 'View All News', kh: 'មើលព័ត៌មានទាំងអស់' },
    'View All Services': { en: 'View All Services', kh: 'មើលសេវាកម្មទាំងអស់' },
    'Call Now': { en: 'Call Now', kh: 'ហៅឥឡូវនេះ' },
    'Subscribe Now': { en: 'Subscribe Now', kh: 'ចុះឈ្មោះឥឡូវនេះ' },
    'Send Message': { en: 'Send Message', kh: 'ផ្ញើសារ' },
    'Close': { en: 'Close', kh: 'បិទ' },
    'Loading...': { en: 'Loading...', kh: 'កំពុងផ្ទុក...' },
    'Read Story': { en: 'Read Story', kh: 'អានរឿង' },
    'View Case Study': { en: 'View Case Study', kh: 'ពិនិត្យមើលគម្រោង' },
    'Precision. Innovation. Excellence.': { en: 'Precision. Innovation. Excellence.', kh: 'ភាពត្រឹមត្រូវ. នវានុវត្តន៍. ឧត្តមភាព.' },
    'Published': { en: 'Published', kh: 'បោះពុម្ពផ្សាយ' },
    'Download': { en: 'Download', kh: 'ទាញយក' },
    'Featured': { en: 'Featured', kh: 'លេចធ្លោ' },
    'Latest Release': { en: 'Latest Release', kh: 'ចេញផ្សាយចុងក្រោយ' },
    'Documents': { en: 'Documents', kh: 'ឯកសារ' },
    'Resource Center': { en: 'Resource Center', kh: 'មជ្ឈមណ្ឌលធនធាន' },
    'Doc Collection Title': { en: 'DOC', kh: 'ការប្រមូល' },
    'Doc Collection Title2': { en: 'COLLECTION', kh: 'ឯកសារ' },
    'Doc Collection Desc': { en: 'Access our centralized repository of engineering standards, research papers, technical specifications, and corporate policies.', kh: 'ចូលប្រើប្រាស់ឃ្លាំងទិន្នន័យកណ្តាលនៃស្តង់ដារវិស្វកម្ម ឯកសារស្រាវជ្រាវ លក្ខណៈបច្ចេកទេស និងគោលនយោបាយក្រុមហ៊ុន។' },
    'Search by title or keyword...': { en: 'Search by title or keyword...', kh: 'ស្វែងរកតាមចំណងជើង ឬពាក្យគន្លឹះ...' },
    'Quick Links': { en: 'Quick Links', kh: 'តំណភ្ជាប់រហ័ស' },
    'Categories': { en: 'Categories', kh: 'ប្រភេទ' },

    // Document categories
    'All Types': { en: 'All Types', kh: 'ប្រភេទទាំងអស់' },
    'Engineering': { en: 'Engineering', kh: 'វិស្វកម្ម' },
    'Safety': { en: 'Safety', kh: 'សុវត្ថិភាព' },
    'Research': { en: 'Research', kh: 'ស្រាវជ្រាវ' },
    'Corporate': { en: 'Corporate', kh: 'ក្រុមហ៊ុន' },
    'Technical': { en: 'Technical', kh: 'បច្ចេកទេស' },
    'Case Study': { en: 'Case Study', kh: 'ករណីសិក្សា' },

    // === FOOTER ===
    'Explore': { en: 'Explore', kh: 'រុករក' },
    'Capabilities': { en: 'Capabilities', kh: 'សមត្ថភាព' },
    'News & Insights': { en: 'News & Insights', kh: 'ព័ត៌មាន & ចំណេះដឹង' },
    'General Construction': { en: 'General Construction', kh: 'សំណង់ទូទៅ' },
    'MEP Engineering': { en: 'MEP Engineering', kh: 'វិស្វកម្ម MEP' },
    'Steel Structure': { en: 'Steel Structure', kh: 'រចនាសម្ព័ន្ធដែក' },
    'Privacy Policy': { en: 'Privacy Policy', kh: 'គោលការណ៍ឯកជនភាព' },
    'Terms of Service': { en: 'Terms of Service', kh: 'លក្ខខណ្ឌប្រើប្រាស់' },
    'All rights reserved': { en: 'All rights reserved', kh: 'រក្សាសិទ្ធិគ្រប់យ៉ាង' },
    'Phnom Penh, Cambodia': { en: 'Phnom Penh, Cambodia', kh: 'ភ្នំពេញ, កម្ពុជា' },
    'Cinematic': { en: 'Cinematic', kh: 'ភាពយន្ត' },
    'Gallery': { en: 'Gallery', kh: 'វិចិត្រសាល' },
    'Construction & Investment': { en: 'Construction & Investment', kh: 'សំណង់ & វិនិយោគ' },
    'Footer Desc': {
        en: 'Engineering the future of Cambodia since 1999. Delivering excellence in high-rise, infrastructure, and industrial construction with unwavering commitment to quality and safety.',
        kh: 'កសាងអនាគតរបស់កម្ពុជាតាំងពីឆ្នាំ ១៩៩៩។ ផ្តល់ជូននូវឧត្តមភាពក្នុងការសាងសង់អគារខ្ពស់ ហេដ្ឋារចនាសម្ព័ន្ធ និងឧស្សាហកម្ម ដោយមានការប្តេជ្ញាចិត្តខ្ពស់ចំពោះគុណភាព និងសុវត្ថិភាព។'
    },

    // === HOME PAGE ===
    'Why Choose Kimmex': { en: 'Why Choose Kimmex', kh: 'ហេតុអ្វីជ្រើសរើស Kimmex' },
    'Experience & Excellence': { en: 'Experience & Excellence', kh: 'បទពិសោធន៍ & ឧត្តមភាព' },
    'Industry Leadership': { en: '25+ Years of Industry Leadership', kh: 'ភាពដឹកនាំក្នុងឧស្សាហកម្មជាង ២៥ឆ្នាំ' },
    'Experience Desc': { en: "With over 25 years of experience, we have established ourselves as Cambodia's most trusted construction partner, delivering projects that stand the test of time.", kh: 'ជាមួយនឹងបទពិសោធន៍ជាង ២៥ឆ្នាំ យើងបានបង្កើតខ្លួនយើងជាដៃគូសាងសង់ដែលគួរឱ្យទុកចិត្តបំផុតរបស់កម្ពុជា ដោយផ្តល់ជូននូវគម្រោងដែលស្ថិតស្ថេរតាមពេលវេលា។' },
    'Safety First': { en: 'Safety First', kh: 'សុវត្ថិភាពជាចំបង' },
    'Zero accident policy': { en: 'Zero accident policy', kh: 'គោលនយោបាយគ្រោះថ្នាក់សូន្យ' },
    'ISO Certified': { en: 'ISO Certified', kh: 'វិញ្ញាបនប័ត្រ ISO' },
    '9001:2015 standards': { en: '9001:2015 standards', kh: 'ស្តង់ដារ ៩០០១:២០១៥' },
    'On-Time Delivery': { en: 'On-Time Delivery', kh: 'ការប្រគល់ជូនទាន់ពេល' },
    '98% completion rate': { en: '98% completion rate', kh: 'អត្រាបញ្ចប់ ៩៨%' },
    'Quality Focus': { en: 'Quality Focus', kh: 'ផ្ដោតលើគុណភាព' },
    'Exceeding expectations': { en: 'Exceeding expectations', kh: 'លើសពីការរំពឹងទុក' },
    'Learn More About Us': { en: 'Learn More About Us', kh: 'ស្វែងយល់បន្ថែមអំពីយើង' },
    'Years of Excellence': { en: 'Years of Excellence', kh: 'ឆ្នាំនៃឧត្តមភាព' },
    'Our Services': { en: 'Our Services', kh: 'សេវាកម្មរបស់យើង' },
    'Comprehensive Construction Solutions': { en: 'Comprehensive Construction Solutions', kh: 'ដំណោះស្រាយសំណង់គ្រប់ជ្រុងជ្រោយ' },
    'From design to completion': { en: 'From design to completion, we offer end-to-end construction services tailored to your needs.', kh: 'ពីការរចនារហូតដល់ការបញ្ចប់ យើងផ្តល់ជូននូវសេវាកម្មសាងសង់ពេញលេញដែលតម្រូវតាមតម្រូវការរបស់អ្នក។' },
    'Our Process': { en: 'Our Process', kh: 'ដំណើរការរបស់យើង' },
    'How We Work': { en: 'How We Work', kh: 'របៀបដែលយើងធ្វើការ' },
    'A streamlined approach': { en: 'A streamlined approach ensuring quality, efficiency, and transparency at every stage.', kh: 'វិធីសាស្រ្តសម្របសម្រួលដែលធានានូវគុណភាព ប្រសិទ្ធភាព និងតម្លាភាពនៅគ្រប់ដំណាក់កាល។' },
    'Consultation': { en: 'Consultation', kh: 'ការពិគ្រោះយោបល់' },
    'Consultation Desc': { en: 'Understanding your vision and requirements', kh: 'ស្វែងយល់ពីចក្ខុវិស័យ និងតម្រូវការរបស់អ្នក' },
    'Planning': { en: 'Planning', kh: 'ការរៀបចំផែនការ' },
    'Planning Desc': { en: 'Detailed blueprints and project timeline', kh: 'ប្លង់លម្អិត និងកាលវិភាគគម្រោង' },
    'Construction': { en: 'Construction', kh: 'ការសាងសង់' },
    'Construction Desc': { en: 'Expert execution with safety first', kh: 'ការអនុវត្តដោយអ្នកជំនាញជាមួយសុវត្ថិភាពជាចំបង' },
    'Handover': { en: 'Handover', kh: 'ការប្រគល់ជូន' },
    'Handover Desc': { en: 'Quality inspection and delivery', kh: 'ការត្រួតពិនិត្យគុណភាព និងការប្រគល់ជូន' },
    'Our Portfolio': { en: 'Our Portfolio', kh: 'ស្នាដៃរបស់យើង' },
    'Featured Projects': { en: 'Featured Projects', kh: 'គម្រោងលេចធ្លោ' },
    'Testimonials': { en: 'Testimonials', kh: 'មតិអតិថិជន' },
    'What Our Clients Say': { en: 'What Our Clients Say', kh: 'អ្វីដែលអតិថិជនរបស់យើងនិយាយ' },
    'Home Testimonials Desc': { en: 'Trusted by government ministries, international organizations, and leading corporations.', kh: 'ទទួលបានការទុកចិត្តពីក្រសួងរដ្ឋាភិបាល អង្គការអន្តរជាតិ និងក្រុមហ៊ុនឈានមុខនានា។' },
    'Latest Insights': { en: 'Latest Insights', kh: 'ការយល់ដឹងចុងក្រោយបំផុត' },
    'Ready to Start Your Project?': { en: 'Ready to Start Your Project?', kh: 'ត្រៀមខ្លួនរួចរាល់ក្នុងការចាប់ផ្តើមគម្រោងរបស់អ្នកហើយឬនៅ?' },
    'Home CTA Desc': { en: "Contact us today for a free consultation and let's build something extraordinary together.", kh: 'ទាក់ទងមកយើងថ្ងៃនេះសម្រាប់ការពិគ្រោះយោបល់ឥតគិតថ្លៃ ហើយមករួមគ្នាបង្កើតអ្វីដែលអស្ចារ្យ។' },
    'Our Partners': { en: 'Our Partners', kh: 'ដៃគូរបស់យើង' },
    'Trusted By Leading Institutions': { en: 'Trusted By Leading Institutions', kh: 'ទុកចិត្តដោយស្ថាប័នឈានមុខ' },

    // === ABOUT US PAGE ===
    'About Kimmex': { en: 'About Kimmex', kh: 'អំពី Kimmex' },
    'ABOUT US headline': { en: 'ABOUT US', kh: 'អំពីយើង' },
    'Our Story': { en: 'Our Story', kh: 'ប្រវត្តិរបស់យើង' },
    'Vision & Mission': { en: 'Vision & Mission', kh: 'ចក្ខុវិស័យ & បេសកកម្ម' },
    'Our Values': { en: 'Our Values', kh: 'គុណតម្លៃរបស់យើង' },
    'Our Leadership': { en: 'Our Leadership', kh: 'ថ្នាក់ដឹកនាំរបស់យើង' },
    'Decades of Excellence': { en: 'Decades of Excellence', kh: 'ឧត្តមភាពរាប់ទសវត្សរ៍' },
    'About Hero Sub': { en: 'Since 1999, Kimmex has been at the forefront of Cambodia\'s construction industry, building the foundation for a modern nation.', kh: 'តាំងពីឆ្នាំ ១៩៩៩ Kimmex បានស្ថិតនៅជួរមុខនៃឧស្សាហកម្មសំណង់របស់កម្ពុជា ដោយកសាងមូលដ្ឋានគ្រឹះសម្រាប់ប្រជាជាតិទំនើប។' },
    'Mission': { en: 'Mission', kh: 'បេសកកម្ម' },
    'Vision': { en: 'Vision', kh: 'ចក្ខុវិស័យ' },
    'Goal': { en: 'Goal', kh: 'គោលដៅ' },
    'Integrity': { en: 'Integrity', kh: 'សុចរិតភាព' },
    'Excellence': { en: 'Excellence', kh: 'ឧត្តមភាព' },
    'Partnership': { en: 'Partnership', kh: 'ភាពជាដៃគូ' },
    'Innovation': { en: 'Innovation', kh: 'នវានុវត្តន៍' },
    'Safety First Value': { en: 'Safety First', kh: 'សុវត្ថិភាពជាចំបង' },
    'Growth': { en: 'Growth', kh: 'ការរីកចម្រើន' },
    'Integrity Desc': { en: 'Honesty and ethical behavior in everything we do.', kh: 'ភាពស្មោះត្រង់ និងក្រមសីលធម៌ក្នុងការងារគ្រប់យ៉ាងរបស់យើង។' },
    'Excellence Desc Value': { en: 'Striving for highest quality standards in all projects.', kh: 'ការខិតខំប្រឹងប្រែងសម្រាប់ស្តង់ដារគុណភាពខ្ពស់បំផុតក្នុងគ្រប់គម្រោង។' },
    'Partnership Desc': { en: 'Building lasting relationships with our clients and partners.', kh: 'កសាងទំនាក់ទំនងយូរអង្វែងជាមួយអតិថិជន និងដៃគូរបស់យើង។' },
    'Innovation Desc': { en: 'Embracing new technologies and creative solutions.', kh: 'ទទួលយកបច្ចេកវិទ្យាថ្មីៗ និងដំណោះស្រាយប្រកបដោយភាពច្នៃប្រឌិត។' },
    'Safety Desc': { en: 'Ensuring the well-being of our team and the public.', kh: 'ធានាសុខុមាលភាពរបស់ក្រុមការងារ និងសាធារណជន។' },
    'Growth Desc': { en: 'Continuous improvement and expanding our capabilities.', kh: 'ការកែលម្អជាបន្តបន្ទាប់ និងការពង្រីកសមត្ថភាពរបស់យើង។' },
    'Teamwork': { en: 'Teamwork', kh: 'ការងារជាក្រុម' },
    'Who We Are': { en: 'Who We Are', kh: 'តើយើងជានរណា' },
    'Cambodia Premier Partner': { en: 'Cambodia\'s Premier Construction Partner', kh: 'ដៃគូសាងសង់ឈានមុខគេនៅកម្ពុជា' },
    'Who We Are Desc Headline': { en: "Kim Mex Construction & Investment Co.,Ltd. Company has formerly named Kim Mex Construction & Investment Co.,Ltd, was established since 1999 and eligible to bid being a company duly registered in accordance with regulation and law in the Kingdom of Cambodia.", kh: 'ក្រុមហ៊ុន គីម ម៉ិច ខនស្រ្តាក់សិន & អ៊ិនវេសមេន ភីអិលស៊ី ពីមុនមានឈ្មោះថា គីម ម៉ិច ខនស្រ្តាក់សិន & អ៊ិនវេសមេន ត្រូវបានបង្កើតឡើងតាំងពីឆ្នាំ ១៩៩៩ និងមានសិទ្ធិចូលរួមដេញថ្លៃជាក្រុមហ៊ុនដែលបានចុះបញ្ជីត្រឹមត្រូវតាមបទប្បញ្ញត្តិ និងច្បាប់នៃព្រះរាជាណាចក្រកម្ពុជា។' },
    'BUILDING': { en: 'BUILDING', kh: 'ការកសាង' },
    'CAMBODIA FUTURE': { en: "CAMBODIA'S FUTURE", kh: 'អនាគតរបស់កម្ពុជា' },
    'About Hero Body': { en: "For over 25 years, KIM MEX Construction has been at the forefront of Cambodia's infrastructure development, transforming visions into landmarks.", kh: 'អស់រយៈពេលជាង ២៥ ឆ្នាំមកហើយ ដែលក្រុមហ៊ុន KIM MEX Construction បានស្ថិតនៅជួរមុខនៃការអភិវឌ្ឍន៍ហេដ្ឋារចនាសម្ព័ន្ធរបស់កម្ពុជា ដោយផ្លាស់ប្តូរចក្ខុវិស័យទៅជាសមិទ្ធផលពិតប្រាកដ។' },
    'Years Experience': { en: 'Years Experience', kh: 'ឆ្នាំបទពិសោធន៍' },
    'Projects Completed': { en: 'Projects Completed', kh: 'គម្រោងដែលបានបញ្ចប់' },
    'Team Members': { en: 'Team Members', kh: 'សមាជិកក្រុម' },
    'Client Satisfaction': { en: 'Client Satisfaction', kh: 'ការពេញចិត្តរបស់អតិថិជន' },
    'Message from CEO': { en: 'Message from CEO', kh: 'សារពីអគ្គនាយក' },
    'CEO Message Body': { en: 'Construction is not just about concrete and steel. It\'s about building trust, fostering communities, and leaving a legacy that stands the test of time. At KIM MEX, we pour our heart into every foundation we lay.', kh: 'ការសាងសង់មិនមែនគ្រាន់តែជាបេតុង និងដែកនោះទេ។ វាគឺអំពីការកសាងទំនុកចិត្ត ការចិញ្ចឹមបីបាច់សហគមន៍ និងការបន្សល់ទុកនូវមរតកដែលស្ថិតស្ថេរតាមពេលវេលា។ នៅ KIM MEX យើងដាក់បេះដូងរបស់យើងទៅក្នុងរាល់គ្រឹះដែលយើងចាក់។' },
    'Founder & CEO': { en: 'Founder & CEO', kh: 'ស្ថាបនិក & អគ្គនាយក' },
    'What Drives Us': { en: 'What Drives Us', kh: 'អ្វីដែលជំរុញយើង' },
    'Our Core Values': { en: 'Our Core Values', kh: 'គុណតម្លៃស្នូលរបស់យើង' },
    'Verified Leadership': { en: 'Verified Leadership', kh: 'ភាពដឹកនាំដែលបានបញ្ជាក់' },
    'Executive Biography': { en: 'Executive Biography', kh: 'ប្រវត្តិរូបសង្ខេបថ្នាក់ដឹកនាំ' },
    'Full Biography': { en: 'Full Biography', kh: 'ប្រវត្តិរូបពេញលេញ' },
    'Directorate': { en: 'Directorate', kh: 'គណៈនាយក' },
    'KIMMEX GROUP': { en: 'KIMMEX GROUP', kh: 'គីម ម៉ិច គ្រុប' },
    'Years': { en: 'Years', kh: 'ឆ្នាំ' },
    'Our Journey': { en: 'Our Journey', kh: 'ដំណើររបស់យើង' },
    'Company Milestones': { en: 'Company Milestones', kh: 'សមិទ្ធផលសំខាន់ៗរបស់ក្រុមហ៊ុន' },
    'View Details': { en: 'View Details', kh: 'មើលព័ត៌មានលម្អិត' },
    'KIM MEX Organization Structure': { en: 'KIM MEX ORGANIZATION STRUCTURE', kh: 'រចនាសម្ព័ន្ធស្ថាប័ន គីម ម៉ិច' },
    'Management & Operations Hierarchy': { en: 'Management & Operations Hierarchy', kh: 'ចំណាត់ថ្នាក់គ្រប់គ្រង និងប្រតិបត្តិការ' },
    'Our Standards': { en: 'Our Standards', kh: 'ស្តង់ដាររបស់យើង' },
    'Quality & Safety First Header': { en: 'Quality & Safety First', kh: 'គុណភាព និងសុវត្ថិភាពជាចំបង' },
    'Safety Desc Body': { en: 'We implement rigorous Quality Assurance (QA) and Quality Control (QC) protocols on every site. Our safety record is a testament to our commitment to our workforce and our clients.', kh: 'យើងអនុវត្តពិធីការធានាគុណភាព (QA) និងការត្រួតពិនិត្យគុណភាព (QC) យ៉ាងតឹងរ៉ឹងនៅគ្រប់ការដ្ឋាន។ កំណត់ត្រាសុវត្ថិភាពរបស់យើងគឺជាសក្ខីភាពនៃការប្តេជ្ញាចិត្តរបស់យើងចំពោះកម្លាំងពលកម្ម និងអតិថិជនរបស់យើង។' },
    'Quality Management Certified': { en: 'Quality Management Certified', kh: 'វិញ្ញាបនប័ត្រគ្រប់គ្រងគុណភាព' },
    'Zero Accidents': { en: 'Zero Accidents', kh: 'គ្រោះថ្នាក់សូន្យ' },
    'Safety record policy': { en: 'Safety record policy', kh: 'គោលនយោបាយកំណត់ត្រាសុវត្ថិភាព' },
    '100% Compliance': { en: '100% Compliance', kh: 'ការអនុលោមតាម ១០០%' },
    'Building code adherence': { en: 'Building code adherence', kh: 'ការគោរពតាមក្រមសីលធម៌សំណង់' },
    'Safety Inspection': { en: 'Safety Inspection', kh: 'ការត្រួតពិនិត្យសុវត្ថិភាព' },
    '9001:2015 Certified': { en: '9001:2015 Certified', kh: 'វិញ្ញាបនប័ត្រ ៩០០១:២០១៥' },
    'Ready to Build Together?': { en: 'Ready to Build Together?', kh: 'ត្រៀមខ្លួនសហការកសាងជាមួយគ្នាហើយឬនៅ?' },
    'About CTA Desc': { en: 'Partner with Cambodia\'s most trusted construction company for your next project.', kh: 'ក្លាយជាដៃគូជាមួយក្រុមហ៊ុនសំណង់ដែលគួរឱ្យទុកចិត្តបំផុតរបស់កម្ពុជាសម្រាប់គម្រោងបន្ទាប់របស់អ្នក។' },
    'KM Group Branding': { en: 'KIM MEX CONSTRUCTION & INVESTMENT CO., LTD.', kh: 'ក្រុមហ៊ុន គីម ម៉ិច ខនស្រ្តាក់សិន & អ៊ិនវេសមេន' },
    // === NEWS PAGE ===
    'NEWSROOM': { en: 'NEWSROOM', kh: 'បន្ទប់ព័ត៌មាន' },
    'INSIGHTS & UPDATES': { en: 'INSIGHTS & UPDATES', kh: 'ចំណេះដឹង & បច្ចុប្បន្នភាព' },
    'Newsroom Subtitle': {
        en: 'Your central hub for the latest construction announcements, project milestones, and industry insights from Kimmex.',
        kh: 'មជ្ឈមណ្ឌលសម្រាប់សេចក្តីប្រកាសសំណង់ចុងក្រោយបំផុត សមិទ្ធផលគម្រោង និងចំណេះដឹងឧស្សាកម្មពី Kimmex។'
    },
    'Featured Story': { en: 'Featured Story', kh: 'រឿងរ៉ាវលេចធ្លោ' },
    'Trending': { en: 'Trending', kh: 'ពេញនិយម' },
    'Trending Now': { en: 'Trending Now', kh: 'កំពុងពេញនិយម' },
    'View All Trends': { en: 'View All Trends', kh: 'មើលការពេញនិយមទាំងអស់' },
    'The Archives': { en: 'The Archives', kh: 'បណ្ណសារ' },
    'LATEST': { en: 'LATEST', kh: 'ចុងក្រោយបំផុត' },
    'STORIES': { en: 'STORIES', kh: 'រឿងរ៉ាវ' },
    'Latest Stories': { en: 'Latest Stories', kh: 'រឿងរ៉ាវចុងក្រោយ' },
    'Clear Filter': { en: 'Clear Filter', kh: 'លុបការចម្រាញ់' },
    'STAY AHEAD OF': { en: 'STAY AHEAD OF', kh: 'បន្តនាំមុខ' },
    'THE CURVE': { en: 'THE CURVE', kh: 'និន្នាការ' },
    'Newsletter Desc': { en: "Subscribe to our newsletter for exclusive insights on Cambodia's construction landscape, project updates, and industry analysis.", kh: 'ចុះឈ្មោះសម្រាប់ព្រឹត្តិប័ត្រព័ត៌មានរបស់យើង ដើម្បីទទួលបានការយល់ដឹងផ្តាច់មុខអំពីទិដ្ឋភាពសំណង់របស់កម្ពុជា បច្ចុប្បន្នភាពគម្រោង និងការវិភាគឧស្សាហកម្ម។' },
    'Email Address': { en: 'Email Address', kh: 'អាសយដ្ឋានអ៊ីមែល' },
    'All Stories': { en: 'All Stories', kh: 'រឿងរ៉ាវទាំងអស់' },
    'Topics': { en: 'Topics', kh: 'ប្រធានបទ' },
    'All': { en: 'All', kh: 'ទាំងអស់' },
    'All Years': { en: 'All Years', kh: 'ឆ្នាំទាំងអស់' },
    'No stories found': { en: 'No stories found', kh: 'រកមិនឃើញរឿងរ៉ាវណាមួយ' },
    'No stories desc': { en: "We couldn't find any news matching your current filters. Try selecting a different topic or year.", kh: 'យើងមិនអាចស្វែងរកព័ត៌មានដែលត្រូវនឹងការចម្រាញ់របស់អ្នកបានទេ។ ព្យាយាមជ្រើសរើសប្រធានបទ ឬឆ្នាំផ្សេងទៀត។' },
    'Reset All Filters': { en: 'Reset All Filters', kh: 'កំណត់ការចម្រាញ់ឡើងវិញ' },
    'Load More Stories': { en: 'Load More Stories', kh: 'ផ្ទុកព័ត៌មានបន្ថែម' },
    'By': { en: 'By', kh: 'ដោយ' },
    'Related Topics': { en: 'Related Topics', kh: 'ប្រធានបទពាក់ព័ន្ធ' },
    'Content Specialist': { en: 'Content Specialist', kh: 'អ្នកជំនាញមាតិកា' },
    'Project Documents': { en: 'Project Documents', kh: 'ឯកសារគម្រោង' },
    'Event Gallery': { en: 'Event Gallery', kh: 'រូបភាពកម្មវិធី' },
    'Latest News': { en: 'Latest News', kh: 'ព័ត៌មានចុងក្រោយ' },
    'Back to Newsroom': { en: 'Back to Newsroom', kh: 'ត្រឡប់ទៅបន្ទប់ព័ត៌មាន' },

    // News categories (used with t() in filter tabs)
    'Project Updates': { en: 'Project Updates', kh: 'ព័ត៌មានបច្ចុប្បន្ន​គម្រោង' },
    'Awards': { en: 'Awards', kh: 'រង្វាន់' },
    'Sustainability': { en: 'Sustainability', kh: 'និរន្តរភាព' },
    'Culture': { en: 'Culture', kh: 'វប្បធម៌' },

    // === HOME PAGE HERO & CAROUSEL ===
    'Home Hero Body': { en: 'Cambodia\'s premier construction company delivering world-class infrastructure, commercial buildings, and government projects with precision and excellence.', kh: 'ក្រុមហ៊ុនសំណង់ឈានមុខគេរបស់កម្ពុជាដែលផ្ដល់ជូននូវហេដ្ឋារចនាសម្ព័ន្ធកម្រិតពិភពលោក អាគារពាណិជ្ជកម្ម និងគម្រោងរដ្ឋាភិបាលប្រកបដោយភាពច្បាស់លាស់ និងភាពល្អឥតខ្ចោះ។' },
    'Since 1999': { en: 'Since 1999', kh: 'តាំងពីឆ្នាំ ១៩៩៩' },
    'WE BUILD': { en: 'WE BUILD', kh: 'យើងកសាង' },
    'YOUR VISION': { en: 'YOUR VISION', kh: 'ចក្ខុវិស័យរបស់អ្នក' },
    'Our Projects': { en: 'Our Projects', kh: 'គម្រោងរបស់យើង' },
    'Featured Project': { en: 'Featured Project', kh: 'គម្រោងលេចធ្លោ' },
    'Rating': { en: 'Rating', kh: 'ការវាយតម្លៃ' },
    'ISO': { en: 'ISO', kh: 'ISO' },
    'Scroll': { en: 'Scroll', kh: 'រំកិលចុះ' },
    'High-rise & Office': { en: 'High-rise & Office', kh: 'អាគារខ្ពស់ៗ និងការិយាល័យ' },
    'Factory & Warehouse': { en: 'Factory & Warehouse', kh: 'រោងចក្រ និងឃ្លាំង' },
    'Roads & Bridges': { en: 'Roads & Bridges', kh: 'ផ្លូវ និងស្ពាន' },
    'Management': { en: 'Management', kh: 'ការគ្រប់គ្រង' },
    'Strategic Oversight': { en: 'Strategic Oversight', kh: 'ការត្រួតពិនិត្យយុទ្ធសាស្ត្រ' },
    'Government Infrastructure': { en: 'Government Infrastructure', kh: 'ហេដ្ឋារចនាសម្ព័ន្ធរដ្ឋាភិបាល' },
    'Commercial Excellence': { en: 'Commercial Excellence', kh: 'ឧត្តមភាពពាណិជ្ជកម្ម' },
    'National Development': { en: 'National Development', kh: 'ការអភិវឌ្ឍជាតិ' },
    'Ministry of Economy': { en: 'Ministry of Economy', kh: 'ក្រសួងសេដ្ឋកិច្ច' },
    'Vattanac Capital Extension': { en: 'Vattanac Capital Extension', kh: 'វឌ្ឍនៈ កាពីតាល់ (គម្រោងពង្រីក)' },
    'Sihanoukville Deep Sea Port': { en: 'Sihanoukville Deep Sea Port', kh: 'កំពង់ផែសមុទ្រទឹកជ្រៅខេត្តព្រះសីហនុ' },
    'Slide 1 Desc': { en: 'A landmark of modern governance and architectural excellence in the heart of Phnom Penh.', kh: 'ជានិមិត្តរូបនៃអភិបាលកិច្ចទំនើប និងឧត្តមភាពស្ថាបត្យកម្មនៅចំកណ្តាលរាជធានីភ្នំពេញ។' },
    'Slide 2 Desc': { en: 'Pushing the boundaries of vertical design and engineering for Cambodia’s premium business hub.', kh: 'ការជំរុញព្រំដែននៃការរចនាបញ្ឈរ និងវិស្វកម្មសម្រាប់មជ្ឈមណ្ឌលអាជីវកម្មលំដាប់ខ្ពស់របស់កម្ពុជា។' },
    'Slide 3 Desc': { en: 'Building the gateway to global trade with robust maritime infrastructure.', kh: 'ការកសាងច្រកទ្វារទៅកាន់ពាណិជ្ជកម្មពិភពលោកជាមួយនឹងហេដ្ឋារចនាសម្ព័ន្ធដែនសមុទ្រដ៏រឹងមាំ។' },
    'View Project': { en: 'View Project', kh: 'មើលគម្រោង' },
    'Years Exp': { en: 'Years Exp', kh: 'ឆ្នាំបទពិសោធន៍' },
    'Partners': { en: 'Partners', kh: 'ដៃគូសហការ' },
    'Years Trust': { en: 'Years Trust', kh: 'ឆ្នាំនៃការទុកចិត្ត' },

    // === PROJECTS PAGE ===
    'Success Stories': { en: 'Success Stories', kh: 'រឿងរ៉ាវជោគជ័យ' },
    'Completed Projects Sub': { en: 'A portfolio of successfully delivered landmarks, infrastructure, and commercial developments across Cambodia.', kh: 'កម្រងស្នាដៃនៃសមិទ្ធផលសំខាន់ៗ ហេដ្ឋារចនាសម្ព័ន្ធ និងការអភិវឌ្ឍន៍ពាណិជ្ជកម្មដែលបានបញ្ចប់ដោយជោគជ័យនៅទូទាំងប្រទេសកម្ពុជា។' },
    'Project In Progress Sub': { en: 'Current developments showcasing our ongoing commitment to excellence and national growth.', kh: 'ការអភិវឌ្ឍន៍បច្ចុប្បន្នដែលបង្ហាញពីការប្តេជ្ញាចិត្តឥតឈប់ឈររបស់យើងចំពោះឧត្តមភាព និងការរីកចម្រើនរបស់ជាតិ។' },
    'Currently Active': { en: 'Currently Active', kh: 'កំពុងសកម្មបច្ចុប្បន្ន' },
    'IN PROGRESS': { en: 'IN PROGRESS', kh: 'កំពុងអនុវត្ត' },
    'All Portfolio': { en: 'All Portfolio', kh: 'ស្នាដៃទាំងអស់' },
    'No completed projects found': { en: 'No completed projects found matching criteria.', kh: 'រកមិនឃើញគម្រោងដែលបានបញ្ចប់ដែលត្រូវនឹងលក្ខណៈវិនិច្ឆ័យទេ។' },
    'No projects in progress found': { en: 'No projects in progress found.', kh: 'រកមិនឃើញគម្រោងដែលកំពុងអនុវត្តទេ។' },
    'Try adjusting your filters.': { en: 'Try adjusting your filters.', kh: 'ព្យាយាមកែតម្រូវការចម្រាញ់របស់អ្នក។' },
    'Check back soon for updates.': { en: 'Check back soon for updates.', kh: 'សូមពិនិត្យមើលម្ដងទៀតនៅពេលក្រោយសម្រាប់បច្ចុប្បន្នភាព។' },
    'Back to Done Projects': { en: 'Back to Done Projects', kh: 'ត្រឡប់ទៅគម្រោងដែលបានបញ្ចប់' },
    'Back to Implementation': { en: 'Back to Implementation', kh: 'ត្រឡប់ទៅគម្រោងដែលកំពុងអនុវត្ត' },
    'Edit Project': { en: 'Edit Project', kh: 'កែសម្រួលគម្រោង' },
    'Project Overview': { en: 'Project Overview', kh: 'ទិដ្ឋភាពទូទៅនៃគម្រោង' },
    'The Background': { en: 'The Background', kh: 'ប្រវត្តិ' },
    'Objectives': { en: 'Objectives', kh: 'គោលបំណង' },
    'Design Concept': { en: 'Design Concept', kh: 'គំនិតរចនា' },
    'Scope of Work': { en: 'Scope of Work', kh: 'វិសាលភាពនៃការងារ' },
    'Key Challenges & Solutions': { en: 'Key Challenges & Solutions', kh: 'បញ្ហាប្រឈម & ដំណោះស្រាយសំខាន់ៗ' },
    'Project Data': { en: 'Project Data', kh: 'ទិន្នន័យគម្រោង' },
    'Client': { en: 'Client', kh: 'អតិថិជន' },
    'Built Area': { en: 'Built Area', kh: 'ផ្ទៃក្រឡាសាងសង់' },
    'Year & Status': { en: 'Year & Status', kh: 'ឆ្នាំ & ស្ថានភាព' },
    'Share Project': { en: 'Share Project', kh: 'ចែករំលែកគម្រោង' },
    'Project Gallery': { en: 'Project Gallery', kh: 'រូបភាពគម្រោង' },
    'Similar Projects': { en: 'Similar Projects', kh: 'គម្រោងស្រដៀងគ្នា' },

    // === MILESTONE DETAIL PAGE ===
    'Project Portfolio': { en: 'Project Portfolio', kh: 'ស្នាដៃគម្រោង' },
    'Milestone Highlights': { en: 'Milestone Highlights', kh: 'ចំណុចសំខាន់ៗ' },
    'Impact': { en: 'Impact', kh: 'ផលប៉ះពាល់' },
    'Milestone Impact Desc': { en: 'This period marked a significant phase in our growth, contributing deeply to the nation\'s infrastructure backbone.', kh: 'រយៈពេលនេះបានសម្គាល់ជំហ៊ានដ៏សំខាន់មួយក្នុងការរីកចម្រើនរបស់យើង ដោយមានការចូលរួមចំណែកយ៉ាងស៊ីជម្រៅដល់ស្នូលហេដ្ឋារចនាសម្ព័ន្ធរបស់ជាតិ។' },
    'Projects details recorded in archive': { en: 'Projects details recorded in archive', kh: 'ព័ត៌មានលម្អិតគម្រោងត្រូវបានកត់ត្រាក្នុងប័ណ្ណសាល' },
    'Milestone Archive Desc': { en: 'Detailed project breakdown for this period is available upon request.', kh: 'ការបំបែកគម្រោងលម្អិតសម្រាប់រយៈពេលនេះអាចទទួលបានតាមការស្នើសុំ។' },

    // === DOCUMENT DETAIL PAGE ===
    'Back to Library': { en: 'Back to Library', kh: 'ត្រឡប់ទៅបណ្ណាល័យ' },
    'Executive Summary': { en: 'Executive Summary', kh: 'សង្ខេបការគ្រប់គ្រង' },
    'Keywords & Topics': { en: 'Keywords & Topics', kh: 'ពាក្យគន្លឹះ & ប្រធានបទ' },
    'Document Preview': { en: 'Document Preview', kh: 'ការមើលសៀវភៅ' },
    'Page 1 of': { en: 'Page 1 of', kh: 'ទំព័រ ១ ក្នុងចំណោម' },
    'Read Full Document': { en: 'Read Full Document', kh: 'អានឯកសារពេញ' },
    'Confidential': { en: 'Confidential', kh: 'សម្ងាត់' },
    'Download File': { en: 'Download File', kh: 'ទាញយកឯកសារ' },
    'Preview Online': { en: 'Preview Online', kh: 'បន្ថែមមើលអនឡាញ' },
    'Share Link': { en: 'Share Link', kh: 'ចែករំលែកតំណ' },
    'Copied!': { en: 'Copied!', kh: 'បានចម្លង!' },
    'Print Info': { en: 'Print Info', kh: 'បោះពុម្ព' },
    'Technical Details': { en: 'Technical Details', kh: 'ព័ត៌មានបច្ចេកទេស' },
    'Document ID': { en: 'Document ID', kh: 'លេខសម្គាល់ឯកសារ' },
    'Language': { en: 'Language', kh: 'ភាសា' },
    'Access Level': { en: 'Access Level', kh: 'កម្រិតចូលប្រើ' },
    'Public': { en: 'Public', kh: 'សាធារណៈ' },
    'License': { en: 'License', kh: 'អាជ្ញាប័ណ្ណ' },
    'Proprietary': { en: 'Proprietary', kh: 'កម្មសិទ្ធ' },
    'Need Assistance?': { en: 'Need Assistance?', kh: 'ត្រូវការជំនួយ?' },
    'Doc Support Desc': { en: 'Contact the Engineering Standards Committee for clarification on this document.', kh: 'ទាក់ទងគណៈកម្មាធិការស្តង់ដារវិស្វកម្មសម្រាប់ការបំភ្លឺអំពីឯកសារនេះ។' },
    'Contact Support': { en: 'Contact Support', kh: 'ទាក់ទងអ្នកគ្រប់គ្រង' },
    'Related Resources': { en: 'Related Resources', kh: 'ធនធានដែលពាក់ព័ន្ធ' },
    'Read': { en: 'Read', kh: 'អាន' },
    'Pages': { en: 'Pages', kh: 'ទំព័រ' },
    'Document': { en: 'Document', kh: 'ឯកសារ' },
    'Last Updated': { en: 'Last Updated', kh: 'ថ្ងៃធ្វើបច្ចុប្បន្នភាពចុងក្រោយ' },
    'Approved': { en: 'Approved', kh: 'បានអនុម័ត' },
    'Draft': { en: 'Draft', kh: 'សេចក្តីព្រាង' },
    'Engineering Standard': { en: 'Engineering Standard', kh: 'ស្តង់ដារវិស្វកម្ម' },
    'Research Paper': { en: 'Research Paper', kh: 'ក្រដាសសិក្សា' },

    // === CONTACT PAGE ===
    "Let's Talk": { en: "Let's Talk", kh: 'តោះនិយាយ' },
    'GET IN TOUCH headline': { en: 'GET IN TOUCH', kh: 'ទាក់ទងមកយើង' },
    'Contact Hero Sub': { en: 'Have a project in mind or want to learn more about our services? Our team is ready to assist you.', kh: 'មានគម្រោងនៅក្នុងចិត្ត ឬចង់ស្វែងយល់បន្ថែមអំពីសេវាកម្មរបស់យើង? ក្រុមការងាររបស់យើងរួចរាល់ក្នុងការជួយអ្នក។' },
    'Headquarters': { en: 'Headquarters', kh: 'ទីស្នាក់ការកណ្តាល' },
    'Visit Us': { en: 'Visit Us', kh: 'មកជួបយើង' },
    'Call Us': { en: 'Call Us', kh: 'ទូរស័ព្ទមកយើង' },
    'Mon - Sat, 8am - 5pm': { en: 'Mon - Sat, 8am - 5pm', kh: 'ច័ន្ទ - សៅរ៍ ម៉ោង ៨ព្រឹក - ៥ល្ងាច' },
    'Email Us': { en: 'Email Us', kh: 'អ៊ីមែលមកយើង' },
    'Connect With Us': { en: 'Connect With Us', kh: 'ភ្ជាប់ជាមួយយើង' },
    'View on Google Maps': { en: 'View on Google Maps', kh: 'មើលនៅ Google Maps' },
    'Send a Message': { en: 'Send a Message', kh: 'ផ្ញើសារ' },
    'Contact Form Sub': { en: 'Fill out the form below and our team will get back to you within 24 hours.', kh: 'បំពេញទម្រង់បែបបទខាងក្រោម ហើយក្រុមការងាររបស់យើងនឹងឆ្លើយតបក្នុង ២៤ ម៉ោង។' },
    'Full Name': { en: 'Full Name *', kh: 'ឈ្មោះពេញ *' },
    'Full Name placeholder': { en: 'John Doe', kh: 'ឧ. សុខ ដារ៉ា' },
    'Phone Number': { en: 'Phone Number', kh: 'លេខទូរស័ព្ទ' },
    'Subject': { en: 'Subject *', kh: 'ប្រធានបទ *' },
    'General Inquiry': { en: 'General Inquiry', kh: 'សំណួរទូទៅ' },
    'Project Consultation': { en: 'Project Consultation', kh: 'ការប្រឹក្សាគម្រោង' },
    'Partnership Proposal': { en: 'Partnership Proposal', kh: 'សំណើភាពជាដៃគូ' },
    'Other': { en: 'Other', kh: 'ផ្សេងទៀត' },
    'Message': { en: 'Message *', kh: 'សារ *' },
    'Message placeholder': { en: 'Tell us about your project or inquiry...', kh: 'ប្រាប់យើងអំពីគម្រោង ឬការសាកសួររបស់អ្នក...' },

    // === CAREERS PAGE ===
    'We are Hiring': { en: 'We are Hiring', kh: 'យើងកំពុងជ្រើសរើសបុគ្គលិក' },
    'BUILD YOUR LEGACY line1': { en: 'BUILD YOUR', kh: 'សាងសង់' },
    'BUILD YOUR LEGACY line2': { en: 'LEGACY', kh: 'មត៌កសម្បត្តិ' },
    'BUILD': { en: 'BUILD', kh: 'សាងសង់' },
    'YOUR LEGACY': { en: 'YOUR LEGACY', kh: 'មត៌កសម្បត្តិរបស់អ្នក' },
    'Careers Hero Sub': { en: "Join a team of visionaries. At Kimmex, we don't just construct buildings; we shape the skyline and engineering future of Cambodia.", kh: 'ចូលរួមក្រុមមនុស្សមានចក្ខុវិស័យ។ នៅ Kimmex យើងមិនត្រឹមតែសាងសង់អគារ; យើងកំណត់រូបភាពអនាគតសំណង់របស់កម្ពុជា។' },
    'View Openings': { en: 'View Openings', kh: 'មើលមុខតំណែង' },
    'Apply General': { en: 'Apply General', kh: 'ដាក់ពាក្យទូទៅ' },
    'Active Projects': { en: 'Active Projects', kh: 'គម្រោងសកម្ម' },
    'Top Employer': { en: 'Top Employer', kh: 'និយោជកលំដាប់ខ្ពស់' },
    'Awarded 2024 - 2025': { en: 'Awarded 2024 - 2025', kh: 'ទទួលរង្វាន់ ២០២៤ - ២០២៥' },
    'Why Choose Kimmex?': { en: 'Why Choose Kimmex?', kh: 'ហេតុអ្វីជ្រើស Kimmex?' },
    'Why Choose Kimmex? Sub': { en: 'We offer more than a job. We offer a career that matters, a community that supports, and projects that leave a lasting legacy.', kh: 'យើងផ្តល់ជូនច្រើនជាងការងារ។ យើងផ្តល់ជូននូវវិជ្ជាជីវៈដែលមានន័យ សហគមន៍គាំទ្រ និងគម្រោងដែលទុកនូវមត៌កសម្បត្តិ។' },
    'Why Kimmex?': { en: 'Why Kimmex?', kh: 'ហេតុអ្វី Kimmex?' },
    'Excellence Driven': { en: 'Excellence Driven', kh: 'ជំរុញឧត្តមភាព' },
    'Excellence Driven Desc': { en: 'We set the highest standards in construction, pushing boundaries to deliver projects that outlast generations.', kh: 'យើងកំណត់ស្តង់ដារខ្ពស់បំផុតក្នុងការសាងសង់ ជំរុញព្រំដែនដើម្បីផ្ដល់គម្រោងដែលរស់រានជាង​세代។' },
    'Impactful Work': { en: 'Impactful Work', kh: 'ការងារប៉ះពាល់ជីវិត' },
    'Impactful Work Desc': { en: 'Every project you work on shapes Cambodia\'s infrastructure — roads, hospitals, government buildings that serve millions.', kh: 'គ្រប់គម្រោងដែលអ្នកធ្វើ ចូលរួមកំណត់ហេដ្ឋារចនាសម្ព័ន្ធរបស់កម្ពុជា — ផ្លូវ មន្ទីរពេទ្យ អគាររដ្ឋាភិបាលដែលបម្រើប្រជាជនរាប់លាននាក់។' },
    'Our Culture': { en: 'Our Culture', kh: 'វប្បធម៌ស្ថាប័នរបស់យើង' },
    'Purpose-Driven Work': { en: 'Purpose-Driven Work', kh: 'ការងារដែលមានបំណងច្បាស់' },
    'Purpose-Driven Work Desc': { en: 'Every project contributes to Cambodia\'s growth. Feel the impact of your work every day.', kh: 'គ្រប់គម្រោងចូលរួមដល់ការរីកចម្រើនរបស់កម្ពុជា។ មានអារម្មណ៍ចំពោះផលប៉ះពាល់ការងារអ្នករាល់ថ្ងៃ។' },
    'Mentorship Culture': { en: 'Mentorship Culture', kh: 'វប្បធម៌ណែនាំ' },
    'Mentorship Culture Desc': { en: 'Learn from Cambodia\'s top engineers and project managers. Grow faster with dedicated mentors.', kh: 'រៀនពីវិស្វករ និងអ្នកគ្រប់គ្រងគម្រោងកំពូលរបស់កម្ពុជា។ រីកចម្រើនលឿនជាមួយអ្នកណែនាំ។' },
    'Fast-Track Growth': { en: 'Fast-Track Growth', kh: 'ការរីកចម្រើនលឿន' },
    'Fast-Track Growth Desc': { en: 'Promotions based on merit. Kimmex is where ambitious professionals thrive and rise quickly.', kh: 'ការតម្លើងឋានៈផ្អែកលើបរិញ្ញាស។ Kimmex ជាកន្លែងដែលអ្នកជំនាញមានមហិច្ឆតាលូតលាស់ និងឈានឡើងលឿន។' },
    'Total Rewards': { en: 'Total Rewards', kh: 'រង្វាន់សរុប' },
    'Benefits Headline': { en: 'More Than Just A Salary.', kh: 'ច្រើនជាងប្រាក់ខែ។' },
    'Benefits Sub': { en: 'We invest in your wellbeing, growth, and long-term success with a competitive package designed for top talent.', kh: 'យើងវិនិយោគលើសុខុមាលភាព ការរីកចម្រើន និងជោគជ័យរយៈពេលវែងរបស់អ្នក ជាមួយកញ្ចប់សម្រាប់ទេពកោសល្យ។' },
    'Performance Bonuses': { en: 'Performance Bonuses', kh: 'រង្វាន់ការងារ' },
    'Health Insurance': { en: 'Health Insurance', kh: 'ធានារ៉ាប់រងសុខភាព' },
    'Paid Time Off': { en: 'Paid Time Off', kh: 'ការឈប់សម្រាកដោយមានប្រាក់ខែ' },
    'Training Budget': { en: 'Training Budget', kh: 'ថវិកាបណ្ដុះបណ្ដាល' },
    'Career Development': { en: 'Career Development', kh: 'ការអភិវឌ្ឍ​វិជ្ជាជីវៈ' },
    'Team Retreats': { en: 'Team Retreats', kh: 'ការសម្រាកសម្រួលក្រុម' },
    'Employee Retention': { en: 'Employee Retention', kh: 'ការរក្សាបុគ្គលិក' },
    'What To Expect': { en: 'What To Expect', kh: 'អ្វីដែលត្រូវរំពឹង' },
    'Our Hiring Process': { en: 'Our Hiring Process', kh: 'ដំណើរការជ្រើសរើសបុគ្គលិក' },
    'Our Hiring Process Sub': { en: 'A transparent and efficient process designed to find the best fit — for both you and us.', kh: 'ដំណើរការតម្លាភាព និងប្រសិទ្ធភាពដែលត្រូវបានរចនាឡើងដើម្បីស្វែងរកភាពស្ញប់ស្ញររវាងអ្នក និងយើង។' },
    'Application': { en: 'Application', kh: 'ពាក្យសុំ' },
    'Screening': { en: 'Screening', kh: 'ការត្រងជ្រើស' },
    'Offer': { en: 'Offer', kh: 'ការស្នើ' },
    'Current Openings': { en: 'Current Openings', kh: 'មុខតំណែងបច្ចុប្បន្ន' },
    'Current Openings Sub': { en: 'Find your place among Cambodia\'s most impactful construction projects.', kh: 'ស្វែងរកទីតាំងរបស់អ្នកក្នុងចំណោមគម្រោងសំណង់ដ៏ប្រែប្រួលបំផុតរបស់កម្ពុជា។' },
    'Search roles...': { en: 'Search roles...', kh: 'ស្វែងរកតំណែង...' },
    'All Departments': { en: 'All Departments', kh: 'ផ្នែកទាំងអស់' },
    'Operations': { en: 'Operations', kh: 'ប្រតិបត្តិការ' },
    'Design': { en: 'Design', kh: 'ការរចនា' },
    'Supply Chain': { en: 'Supply Chain', kh: 'ខ្សែសង្វាក់ផ្គត់ផ្គង់' },
    'Salary Range': { en: 'Salary Range', kh: 'ជួរប្រាក់ខែ' },
    'Experience': { en: 'Experience', kh: 'បទពិសោធន៍' },
    'Location': { en: 'Location', kh: 'ទីតាំង' },
    'Department': { en: 'Department', kh: 'ផ្នែក' },
    'Full-time': { en: 'Full-time', kh: 'ពេញម៉ោង' },
    'Contract': { en: 'Contract', kh: 'កិច្ចសន្យា' },
    'Part-time': { en: 'Part-time', kh: 'ក្រៅម៉ោង' },
    'View Full Description': { en: 'View Full Description', kh: 'មើលការពណ៌នាពេញ' },
    'No positions found': { en: 'No positions found', kh: 'រកមិនឃើញមុខតំណែង' },
    'No positions found Sub': { en: 'Try adjusting your search or filters to find relevant roles.', kh: 'ព្យាយាមកែប្រែការស្វែងរក ឬការចម្រាញ់ ដើម្បីស្វែងរកតំណែងដែលពាក់ព័ន្ធ។' },
    'Clear All Filters': { en: 'Clear All Filters', kh: 'លុបការចម្រាញ់ទាំងអស់' },
    "Don't see your perfect role?": { en: "Don't see your perfect role?", kh: 'មិនឃើញតំណែងដែលអ្នកចង់បានទេ?' },
    'Talent Pool Sub': { en: "We're always looking for exceptional people. Send us your details and we'll keep you in mind for future opportunities.", kh: 'យើងតែងតែស្វែងរកមនុស្សពូកែ។ ផ្ញើព័ត៌មានរបស់អ្នកមកយើង ហើយយើងនឹងដឹងទុករង់ចាំឱកាសថ្មី។' },
    'General Application': { en: 'General Application', kh: 'ពាក្យសុំទូទៅ' },
    'General Application Sub': { en: "Tell us about yourself and we'll reach out when the right opportunity arises.", kh: 'ប្រាប់យើងអំពីខ្លួនអ្នក ហើយយើងនឹងទំនាក់ទំនងនៅពេលមានឱកាសសមស្រប។' },
    'Back to Careers': { en: 'Back to Careers', kh: 'ត្រឡប់ទៅទំព័រអាជីព' },
    'Role Overview': { en: 'Role Overview', kh: 'ទិដ្ឋភាពទូទៅនៃតួនាទី' },
    'Key Responsibilities': { en: 'Key Responsibilities', kh: 'ការទទួលខុសត្រូវសំខាន់ៗ' },
    'Qualifications': { en: 'Qualifications', kh: 'លក្ខណៈសម្បត្តិ' },
    'Benefits & Perks': { en: 'Benefits & Perks', kh: 'អត្ថប្រយោជន៍ និងការលើកទឹកចិត្ត' },
    'Join us as a': { en: 'Join us as a', kh: 'ចូលរួមជាមួយយើងជា' },
    'Share': { en: 'Share', kh: 'ចែករំលែក' },
    'Print': { en: 'Print', kh: 'បោះពុម្ព' },
    'First Name': { en: 'First Name *', kh: 'នាម *' },
    'Last Name': { en: 'Last Name *', kh: 'ត្រកូល *' },
    'Phone Number required': { en: 'Phone Number *', kh: 'លេខទូរស័ព្ទ *' },
    'Area of Interest': { en: 'Area of Interest', kh: 'ផ្នែកចាប់អារម្មណ៍' },
    'Select Department...': { en: 'Select Department...', kh: 'ជ្រើសរើសផ្នែក...' },
    'Resume / CV': { en: 'Resume / CV *', kh: 'ប្រវត្តិរូប / CV *' },
    'Click to Upload or Drag & Drop': { en: 'Click to Upload or Drag & Drop', kh: 'ចុចដើម្បីផ្ទុកឡើង ឬអូសសម្ភារ' },
    'PDF, DOCX up to 5MB': { en: 'PDF, DOCX up to 5MB', kh: 'PDF, DOCX រហូតដល់ 5MB' },
    'Submit Application': { en: 'Submit Application', kh: 'ដាក់ពាក្យ' },
    'Send General Application': { en: 'Send General Application', kh: 'ផ្ញើពាក្យដាក់ទូទៅ' },

    // === TEAM PAGE ===
    'Back to Org Chart': { en: 'Back to Org Chart', kh: 'ត្រឡប់ទៅអង្គការ' },
    'Biography': { en: 'Biography', kh: 'ប្រវត្តិ' },
    'Focus Areas': { en: 'Focus Areas', kh: 'ផ្នែកផ្ដោត' },
    'Credentials': { en: 'Credentials', kh: 'គោលសញ្ញាបត្រ' },
    'Professional Journey': { en: 'Professional Journey', kh: 'ដំណើរវិជ្ជាជីវៈ' },

    // === LOCATIONS & CATEGORIES ===
    'Siem Reap': { en: 'Siem Reap', kh: 'សៀមរាប' },
    'Kandal': { en: 'Kandal', kh: 'កណ្តាល' },
    'Sihanoukville': { en: 'Sihanoukville', kh: 'ព្រះសីហនុ' },
    'Phnom Penh': { en: 'Phnom Penh', kh: 'ភ្នំពេញ' },
    'Kampot': { en: 'Kampot', kh: 'កំពត' },
    'All Locations': { en: 'All Locations', kh: 'ទីតាំងទាំងអស់' },
    'Hiring Step 1 Desc': { en: 'Submit your CV & Portfolio via our portal.', kh: 'ដាក់ CV & ស្នាដៃរបស់អ្នកតាមរយៈប្រព័ន្ធរបស់យើង។' },
    'Hiring Step 2 Desc': { en: 'Initial call with HR to discuss fit & basics.', kh: 'ការហៅទូរស័ព្ទដំបូងជាមួយ HR ដើម្បីពិភាក្សាមូលដ្ឋាន។' },
    'Hiring Step 3 Desc': { en: 'Deep-dive interview with the department led.', kh: 'ការសម្ភាសន៍ស៊ីជម្រៅជាមួយប្រធានផ្នែក។' },
    'Hiring Step 4 Desc': { en: 'Establish terms and welcome you aboard!', kh: 'ទទួលយកការផ្តល់ជូន និងស្វាគមន៍មកកាន់ក្រុម!' },
    'Government': { en: 'Government', kh: 'រដ្ឋាភិបាល' },
    'Commercial': { en: 'Commercial', kh: 'ពាណិជ្ជកម្ម' },
    'Industrial': { en: 'Industrial', kh: 'ឧស្សាហកម្ម' },
    'Water Treatment Plant': { en: 'Water Treatment Plant', kh: 'ស្ថានីយ៍ប្រព្រឹត្តកម្មទឹក' },
    'Slope Construction': { en: 'Slope Construction', kh: 'ការសាងសង់ជម្រាល' },
    'Government Office Building': { en: 'Government Office Building', kh: 'អគារការិយាល័យរដ្ឋាភិបាល' },
    'Completed': { en: 'Completed', kh: 'បានបញ្ចប់' },
    'Under Construction': { en: 'Under Construction', kh: 'កំពុងសាងសង់' },

    // === ADMIN DASHBOARD ===
    'Overview': { en: 'Overview', kh: 'ទិដ្ឋភាពទូទៅ' },
    'Inquiries': { en: 'Inquiries', kh: 'ការសាកសួរ' },
    'Site Content': { en: 'Site Content', kh: 'មាតិកាគេហទំព័រ' },
    'Home Page': { en: 'Home Page', kh: 'ទំព័រដើម' },
    'Hero Section': { en: 'Hero Section', kh: 'ផ្នែក Hero' },
    'Why Choose Us': { en: 'Why Choose Us', kh: 'ហេតុអ្វីជ្រើសរើសយើង' },
    'Working Process': { en: 'Working Process', kh: 'ដំណើរការការងារ' },
    'Service Cards': { en: 'Service Cards', kh: 'កាតសេវាកម្ម' },
    'Sectors We Serve': { en: 'Sectors We Serve', kh: 'វិស័យដែលយើងបម្រើ' },
    'Org Chart (Design Z)': { en: 'Org Chart (Design Z)', kh: 'រចនាសម្ព័ន្ធអង្គការ (Design Z)' },
    'Contact Info': { en: 'Contact Info', kh: 'ព័ត៌មានទំនាក់ទំនង' },
    'Settings': { en: 'Settings', kh: 'ការកំណត់' },
    'Collapse': { en: 'Collapse', kh: 'បង្រួម' },
    'View Website': { en: 'View Website', kh: 'មើលគេហទំព័រ' },
    'Sign Out': { en: 'Sign Out', kh: 'ចាកចេញ' },
    'Administrator': { en: 'Administrator', kh: 'អ្នកគ្រប់គ្រង' },
    'System Settings': { en: 'System Settings', kh: 'ការកំណត់ប្រព័ន្ធ' },
    'Manage your account preferences and site-wide configuration.': { en: 'Manage your account preferences and site-wide configuration.', kh: 'គ្រប់គ្រងចំណូលចិត្តគណនីរបស់អ្នក និងការកំណត់ទូទាំងគេហទំព័រ។' },
    'Save Changes': { en: 'Save Changes', kh: 'រក្សាទុកការផ្លាស់ប្តូរ' },
    'Settings Saved': { en: 'Settings Saved', kh: 'បានរក្សាទុកការកំណត់' },
    'Saving...': { en: 'Saving...', kh: 'កំពុងរក្សាទុក...' },
    'Localization & Typography': { en: 'Localization & Typography', kh: 'មូលដ្ឋានីយកម្ម & អក្សរផ្ចង់' },
    'Khmer Font Family': { en: 'Khmer Font Family', kh: 'ប្រភេទពុម្ពអក្សរខ្មែរ' },
    'Choose the primary font for Khmer (KH) language content across the website.': { en: 'Choose the primary font for Khmer (KH) language content across the website.', kh: 'ជ្រើសរើសពុម្ពអក្សរចម្បងសម្រាប់មាតិកាភាសាខ្មែរ (KH) នៅទូទាំងគេហទំព័រ។' },
    'Account Profile': { en: 'Account Profile', kh: 'ប្រវត្តិរូបគណនី' },
    'Display Name': { en: 'Display Name', kh: 'ឈ្មោះហៅក្រៅ' },
    'CMS Configuration': { en: 'CMS Configuration', kh: 'ការកំណត់ CMS' },
    'Auto-save Content': { en: 'Auto-save Content', kh: 'រក្សាទុកមាតិកាដោយស្វ័យប្រវត្តិ' },
    'Maintenance Mode': { en: 'Maintenance Mode', kh: 'របៀបថែទាំ' },
    'Critical Actions': { en: 'Critical Actions', kh: 'សកម្មភាពសំខាន់ៗ' },
    'Reset System': { en: 'Reset System', kh: 'កំណត់ប្រព័ន្ធឡើងវិញ' },
    'Dashboard Overview': { en: 'Dashboard Overview', kh: 'ទិដ្ឋភាពទូទៅនៃផ្ទាំងគ្រប់គ្រង' },
    'Key metrics and recent activity for KIM MEX CMS.': { en: 'Key metrics and recent activity for KIM MEX CMS.', kh: 'រង្វាស់សំខាន់ៗ និងសកម្មភាពថ្មីៗសម្រាប់ KIM MEX CMS។' },
    'New Project': { en: 'New Project', kh: 'គម្រោងថ្មី' },
    'Total Projects': { en: 'Total Projects', kh: 'គម្រោងសរុប' },
    'Active Team': { en: 'Active Team', kh: 'ក្រុមការងារសកម្ម' },
    'Recent Projects': { en: 'Recent Projects', kh: 'គម្រោងថ្មីៗ' },
    'Project Details': { en: 'Project Details', kh: 'ព័ត៌មានលម្អិតនៃគម្រោង' },
    'Category': { en: 'Category', kh: 'ប្រភេទ' },
    'Activity': { en: 'Activity', kh: 'សកម្មភាព' },
    'Project Distribution': { en: 'Project Distribution', kh: 'ការបែងចែកគម្រោង' },
    'Monthly Growth': { en: 'Monthly Growth', kh: 'កំណើនប្រចាំខែ' },
    'vs last month': { en: 'vs last month', kh: 'ធៀបនឹងខែមុន' },
    'System Status': { en: 'System Status', kh: 'ស្ថានភាពប្រព័ន្ធ' },
    'All systems operational. Content cache synced.': { en: 'All systems operational. Content cache synced.', kh: 'ប្រព័ន្ធទាំងអស់ដំណើរការធម្មតា។ ឃ្លាំងសម្ងាត់មាតិកាត្រូវបានធ្វើសមកាលកម្ម។' },
    'Live Sync Active': { en: 'Live Sync Active', kh: 'សមកាលកម្មបន្តផ្ទាល់កំពុងសកម្ម' },
    'Admin User': { en: 'Admin User', kh: 'អ្នកប្រើប្រាស់គ្រប់គ្រង' },
    'System Default': { en: 'System Default', kh: 'ពុម្ពអក្សរប្រព័ន្ធ' },
    'Classic, clean Khmer font ideal for body text.': { en: 'Classic, clean Khmer font ideal for body text.', kh: 'ពុម្ពអក្សរខ្មែរបែបបុរាណ និងស្អាត ល្អសម្រាប់អត្ថបទតួសេចក្តី។' },
    'Bold, modern display font perfect for headings.': { en: 'Bold, modern display font perfect for headings.', kh: 'ពុម្ពអក្សរដិត និងទំនើប ល្អឥតខ្ចោះសម្រាប់ចំណងជើង។' },
    'Clear and legible, great for both subheadings and body.': { en: 'Clear and legible, great for both subheadings and body.', kh: 'ច្បាស់ និងងាយអាន ល្អសម្រាប់ទាំងចំណងជើងរង និងតួសេចក្តី។' },
    'Uses the default operating system font for Khmer.': { en: 'Uses the default operating system font for Khmer.', kh: 'ប្រើប្រាស់ពុម្ពអក្សរលំនាំដើមរបស់ប្រព័ន្ធប្រតិបត្តិការសម្រាប់ភាសាខ្មែរ។' },
    'Automatically save changes while editing projects and site content.': { en: 'Automatically save changes while editing projects and site content.', kh: 'រក្សាទុកការផ្លាស់ប្តូរដោយស្វ័យប្រវត្តិ ខណៈពេលកំពុងកែសម្រួលគម្រោង និងមាតិកាគេហទំព័រ។' },
    'Redirect all public traffic to a holding page during major updates.': { en: 'Redirect all public traffic to a holding page during major updates.', kh: 'បង្វែររាល់ចរាចរណ៍សាធារណៈទៅកាន់ទំព័ររង់ចាំ អំឡុងពេលការធ្វើបច្ចុប្បន្នភាពធំៗ។' },
    'Resetting the database will permanently clear all project data.': { en: 'Resetting the database will permanently clear all project data.', kh: 'ការកំណត់មូលដ្ឋានទិន្នន័យឡើងវិញនឹងសម្អាតទិន្នន័យគម្រោងទាំងអស់ជាអចិន្ត្រៃយ៍។' },
    'Change Photo': { en: 'Change Photo', kh: 'ផ្លាស់ប្តូររូបភាព' },
    'Manage architectural assets and infrastructure projects.': { en: 'Manage architectural assets and infrastructure projects.', kh: 'គ្រប់គ្រងទ្រព្យសម្បត្តិស្ថាបត្យកម្ម និងគម្រោងហេដ្ឋារចនាសម្ព័ន្ធ។' },
    'Add Project': { en: 'Add Project', kh: 'បន្ថែមគម្រោង' },
    'Search projects...': { en: 'Search projects...', kh: 'ស្វែងរកគម្រោង...' },
    'View Live': { en: 'View Live', kh: 'មើលបន្តផ្ទាល់' },
    'Remove': { en: 'Remove', kh: 'លុបចេញ' },
    'No projects found.': { en: 'No projects found.', kh: 'រកមិនឃើញគម្រោងទេ។' },
    'Adjust your filters or search terms.': { en: 'Adjust your filters or search terms.', kh: 'កែសម្រួលការចម្រាញ់ ឬពាក្យស្វែងរករបស់អ្នក។' },
    'Are you sure you want to delete': { en: 'Are you sure you want to delete', kh: 'តើអ្នកប្រាកដថាចង់លុប' },
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    fontClassName: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('kh');

    const t = (key: string): string => {
        // Remove trailing/leading spaces for lookup
        const lookupKey = key.trim();
        // Return translation or original key if not found
        return dictionary[lookupKey]?.[language] || key;
    };

    const getFontClassName = () => {
        if (language !== 'kh') return 'font-sans';

        switch (configData.khmerFont) {
            case 'Koulen': return koulen.className;
            case 'Siemreap': return siemreap.className;
            case 'System': return 'font-sans';
            case 'Battambang':
            default: return battambang.className;
        }
    };

    const fontClassName = getFontClassName();

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, fontClassName }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}

export function getLocalizedText(textObj: LocalizedString | undefined, lang: Language): string {
    if (!textObj) return '';
    return textObj[lang] || textObj['en'] || '';
}
